apiVersion: v1
kind: Pod
metadata:
  name: ephmeral-container
spec:
  containers:
    - name: sample
      image: busybox:latest
      command: ["sh", "-c", "echo hello-from-busybox > /index.html && httpd -f -p 8080 -h /"]
      ports:
        - containerPort: 8080

# Debug from another pod
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      command: ["sleep", "3600"]

# At cases where we need to be in container to troubleshoot.
# kubectl debug -it ephmeral-container -c debugger --image=nicolaka/netshoot:latest --target=sample --profile=general

