apiVersion: v1
kind: Pod 
metadata:
  name: multi-container-shared-storage

spec:
  volumes:
  - name: sharedstorage
    emptyDir: {}

  containers:
    - name: nginx-container-1
      image: nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: sharedstorage
      initContainers:
        - name: redhat
          image: rkalluru/learnk8s:init-container-html-generator
          volumeMounts:
            - mountPath: /opt
              name: sharedstorages

  